appprincipal/urls.py
from django.conf.urls import url
from django.urls import path
from appprincipal.views import *

app_name = 'appprincipal'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^hist_2015_1$', Hist_2015_1, name="historico_2015"),
    url(r'^hist_2015_2$', Hist_2015_2, name="historico_2015_2"),
    url(r'^hist_2015_3$', Hist_2015_3, name="historico_2015_3"),
    url(r'^hist_2015_4$', Hist_2015_4, name="historico_2015_4"),
    url(r'^hist_2015_5$', Hist_2015_5, name="historico_2015_5"),
    url(r'^hist_2015_6$', Hist_2015_6, name="historico_2015_6"),
    url(r'^hist_2015_7$', Hist_2015_7, name="historico_2015_7"),
    url(r'^hist_2015_8$', Hist_2015_8, name="historico_2015_8"),
    url(r'^hist_2015_9$', Hist_2015_9, name="historico_2015_9"),
    url(r'^hist_2015_10$', Hist_2015_10, name="historico_2015_10"),
    url(r'^hist_2015_11$', Hist_2015_11, name="historico_2015_11"),
    url(r'^hist_2015_12$', Hist_2015_12, name="historico_2015_12"),
    url(r'^hist_2016_1$', Hist_2016_1, name="historico_2016"),
    url(r'^hist_2016_2$', Hist_2016_2, name="historico_2016_2"),
    url(r'^hist_2016_3$', Hist_2016_3, name="historico_2016_3"),
    url(r'^hist_2017_1$', Hist_2017_1, name="historico_2017"),
    #url(r'^pie-chart$', pie_chart, name="pie-chart"),
    #url(r'^situacao_sigla$', hist_2015_view, name="hist_2015_view"),
    url(r'^historico/$', historico, name='historico'),
    url(r'^data/$', pivot_data, name='pivot_data'),
    url(r'^dashboard/$', dashboard_with_pivot, name='dashboard_with_pivot'),
    
    
]

projpad/urls.py
from django import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
#from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appprincipal.urls')),
    ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),

]

appprincipal/forms.py
from projpad.models import *
from django import forms
from django.forms import ModelForm
from projpad.models import *


class HistForm(forms.ModelForm):
    class Meta:
        model = Hist_voo2015
        fields = ['sigla', 'numVoo', 'situacao', 'tipoLinha',  'origem', 'destino']

class HistForm2016(forms.ModelForm):
    class Meta:
        model = Hist_voo2016
        fields = ['sigla', 'numVoo', 'situacao', 'tipoLinha',  'origem', 'destino']

class HistForm2017(forms.ModelForm):
    class Meta:
        model = Hist_voo2017
        fields = ['sigla', 'numVoo', 'situacao', 'tipoLinha', 'origem', 'destino']

class HistForm2018(forms.ModelForm):
    class Meta:
        model = Hist_voo2018
        fields = ['sigla', 'numVoo', 'situacao', 'tipoLinha',  'origem', 'destino'] 

appprincipal/views.py
from django.shortcuts import render, redirect, get_object_or_404
import json
# Create your views here.
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse, JsonResponse
from projpad.models import *
from django.db.models import Sum
from appprincipal.forms import *
from .forms import *
from projpad.models import *
from django.core import serializers
#from chartit import DataPool, Chart, PivotDataPool, PivotChart

def index(request):
    return render(request, 'index.html')


def Hist_2015_1(request):
    item = Hist_voo2015.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Janeiro',
    }
    return render(request, 'hist2015.html', context)


def Hist_2015_2(request):
    item = Hist_voo2015_2.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Fevereiro',
    }
    return render(request, 'hist2015.html', context)


def Hist_2015_3(request):
    item = Hist_voo2015_3.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Março',
    }
    return render(request, 'hist2015.html', context)

def Hist_2015_4(request):
    item = Hist_voo2015_4.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Abril',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_5(request):
    item = Hist_voo2015_5.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Maio',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_6(request):
    item = Hist_voo2015_6.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 junho',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_7(request):
    item = Hist_voo2015_7.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Julho',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_8(request):
    item = Hist_voo2015_8.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Agosto',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_9(request):
    item = Hist_voo2015_9.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Setembro',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_10(request):
    item = Hist_voo2015_10.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Outubro',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_11(request):
    item = Hist_voo2015_11.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2015 Novembro',
    }
    return render(request, 'hist2015.html', context) 

def Hist_2015_12(request):
    item = Hist_voo2015_12.objects.all()    
    context = {
        'item': item,
        'header': 'Historico 2015 Dezembro',
    }
    return render(request, 'hist2015.html', context) 

def historico(request):
    queryset = Hist_voo2015.objects.all()
    sigla = [obj.sigla for obj in queryset]
    situacao = [obj.situacao for obj in queryset]

    context = {
        'sigla': json.dumps(sigla),
        'situacao': json.dumps(situacao),
    }
    return render(request, 'historico.html', context)

def dashboard_with_pivot(request):
    return render(request, 'dashboard_with_pivot.html', {})


def pivot_data(request):
    dataset = Order.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)



def Hist_2016_1(request):
    item = Hist_voo2016.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2016 Janeiro',
    }
    return render(request, 'hist2016.html', context)


def Hist_2016_2(Hist_2016_1):
    pass
    context = {
        'header': 'Historico 2016 Fervereiro',
    }
    return render(Hist_2016_1, 'hist2016.html', context)

def Hist_2016_3(Hist_2016_1):
    pass
    context = {
        'header': 'Historico 2016 Março',
    }
    return render(Hist_2016_1, 'hist2016.html', context)

def Hist_2017_1(request):
    item = Hist_voo2017.objects.all()
    context = {
        'item': item,
        'header': 'Historico 2017 Janeiro',
    }
    return render(request, 'hist2017.html', context)

appprincipal/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>ANAC HISTORICO</title>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Django Highcharts {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}" />

<body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'appprincipal:index' %}">Historico de Voos 2015-2019</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02"
            aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'appprincipal:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'appprincipal:historico_2015' %}">2015</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'appprincipal:historico_2016' %}">2016</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'appprincipal:historico_2017' %}">2017</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">2018</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">2019</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'appprincipal:dashboard_with_pivot' %}" >Gráficos</a>
                </li>
            </ul>

        </div>
    </nav>

    <br>
    <div class="container">

        {% block body %}


        {% endblock%}

    </div>

</body>

</html>

appprincipal/templates/dashboard_with_pivot.html
<html lang="en">
    <input type="button" value="Voltar" onClick="history.go(-1)">
    <input type="button" value="Atualizar" onClick="history.go(0)">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with ANAC</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/">
    <style>
/* Charts Style  */

.fm-charts-color-1 {
  fill: #ffa600 !important;
}

.fm-charts-color-2 {
  fill: #7eae26 !important;
}

.fm-charts-color-3 {
  fill: #00a45a !important;
}

.fm-charts-color-4 {
  fill: #df3800 !important;
}

.fm-charts-color-5 {
  fill: #e95800 !important;
}

.fm-charts-color-6 {
  fill: #ffa600 !important;
}</style>
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'appprincipal:pivot_data' %}"></div>
<div id="pivot-chart-container"></div>
<script>
function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data),
                    mapping: {
                        "product_category": {
                            "caption": "Sigla"
                        },
                        "payment_method": {
                            "caption": "Gráfico Ano XXXX"
                        },
                        "shipping_cost": {
                            "caption": "Número Voo",
                            
                        },
                        "unit_price": {
                            "caption": "Data de Origem",
                            "type": "number"
                        }
                    }
                },
                "slice": {
                    "rows": [{
                        "uniqueName": "product_category"
                    }],
                    "columns": [{
                            "uniqueName": "payment_method"
                        },
                        {
                            "uniqueName": "[Measures]"
                        }
                    ],
                    "measures": [{
                            "uniqueName": "shipping_cost",
                            "aggregation": "sum"
                        },
                        {
                            "uniqueName": "unit_price",
                            "aggregation": "sum"
                        }
                    ]
                }
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data),
                    mapping: {
                        "product_category": {
                            "caption": "Product Category"
                        },
                        "payment_method": {
                            "caption": "Payment Method"
                        },
                        "shipping_cost": {
                            "caption": "Shipping Cost",
                            "type": "number"
                        },
                        "unit_price": {
                            "caption": "Unit Price",
                            "type": "number"
                        }
                    }
                },
                "slice": {
                    "rows": [{
                        "uniqueName": "product_category"
                    }],
                    "columns": [{
                        "uniqueName": "[Measures]"
                    }],
                    "measures": [{
                        "uniqueName": "Price",
                        "formula": "sum(\"shipping_cost\") + sum(\"unit_price\")",
                        "caption": "Price"
                    }]
                },
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
    }
});


</script>
</body>
</html>

appprincipal/templates/hist2015.html
{% extends 'base.html' %}

{% block body %}
<div class="add_buttons">

    <div class="button-group">
        <a href="{% url 'appprincipal:historico_2015' %}" class="btn btn-primary btn-md btn-trim" role="button"> Janeiro</a>
        <a href="{% url 'appprincipal:historico_2015_2' %}" class="btn btn-primary btn-md btn-trim" role="button"> Fevereiro</a>
        <a href="{% url 'appprincipal:historico_2015_3' %}" class="btn btn-primary btn-md btn-trim" role="button"> Março</a>
        <a href="{% url 'appprincipal:historico_2015_4' %}"class="btn btn-primary btn-md btn-trim" role="button"> Abril</a>
        <a href="{% url 'appprincipal:historico_2015_5' %}" class="btn btn-primary btn-md btn-trim" role="button"> Maio</a>
        <a href="{% url 'appprincipal:historico_2015_6' %}" class="btn btn-primary btn-md btn-trim" role="button"> Junho</a>
        <a href="{% url 'appprincipal:historico_2015_7' %}" class="btn btn-primary btn-md btn-trim" role="button"> Julho</a>
        <a href="{% url 'appprincipal:historico_2015_8' %}" class="btn btn-primary btn-md btn-trim" role="button"> Agosto</a>         <a href="{% url 'appprincipal:historico_2015_9' %}" class="btn btn-primary btn-md btn-trim" role="button"> Setembro</a>
        <a href="{% url 'appprincipal:historico_2015_10' %}" class="btn btn-primary btn-md btn-trim" role="button"> Outubro</a>
        <a href="{% url 'appprincipal:historico_2015_11' %}"class="btn btn-primary btn-md btn-trim" role="button"> Novembro</a>
        <a href="{% url 'appprincipal:historico_2015_12' %}" class="btn btn-primary btn-md btn-trim" role="button"> Dezem</a>
    </div>

</div>


<div>

    <h4>Currently Viewing {{ header }}</h4>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>Sigla</th>
            <th>Num. Voo</th>
            <th>Status</th>
            <th>Tipo de Linha</th>
            <th>Data de saída</th>
            <th>Origem</th>
            <th>Destino</th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        {% for item in item %}

        <tr>
            <td>{{ item.pk }}
            <td>{{ item.sigla }}</td>
            <td>{{ item.numVoo }}</td>
            <td>{{ item.situacao }}</td>
            <td>{{ item.tipoLinha }}</td>
            <td>{{ item.data_real }}</td>
            <td>{{ item.origem }}</td>
            <td>{{ item.destino }}</td>

        </tr>

        {% endfor %}
    </tbody>
</table>

{% endblock %}

appprincipal/templates/hist2016.html
{% extends 'base.html' %}

{% block body %}
<div class="add_buttons">

    <div class="button-group">
        <a href="{% url 'appprincipal:historico_2016' %}" class="btn btn-primary btn-md btn-trim" role="button"> Janeiro</a>
        <a href="{% url 'appprincipal:historico_2016_2' %}" class="btn btn-primary btn-md btn-trim" role="button"> Fevereiro</a>
        <a href="{% url 'appprincipal:historico_2016_3' %}" class="btn btn-primary btn-md btn-trim" role="button"> Março</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Abril</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Maio</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Junho</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Julho</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Agosto</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Setembro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Outubro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Novembro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Dezembro</a>
    </div>

</div>


<div>

    <h4>Currently Viewing {{ header }}</h4>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>Sigla</th>
            <th>Num. Voo</th>
            <th>Status</th>
            <th>Tipo de Linha</th>
            <th>Data de saída</th>
            <th>Origem</th>
            <th>Destino</th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        {% for item in item %}

        <tr>
            <td>{{ item.pk }}
            <td>{{ item.sigla }}</td>
            <td>{{ item.numVoo }}</td>
            <td>{{ item.situacao }}</td>
            <td>{{ item.tipoLinha }}</td>
            <td>{{ item.data_real }}</td>
            <td>{{ item.origem }}</td>
            <td>{{ item.destino }}</td>

        </tr>

        {% endfor %}
    </tbody>
</table>

{% endblock %}

appprincipal/templates/hist2017.html
{% extends 'base.html' %}

{% block body %}
<div class="add_buttons">

    <div class="button-group">
        <a href="{% url 'appprincipal:historico_2017' %}" class="btn btn-primary btn-md btn-trim" role="button"> Janeiro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Fevereiro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Março</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Abril</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Maio</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Junho</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Julho</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Agosto</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Setembro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Outubro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Novembro</a>
        <a href="#" class="btn btn-primary btn-md btn-trim" role="button"> Dezembro</a>
    </div>

</div>


<div>

    <h4>Currently Viewing {{ header }}</h4>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>Sigla</th>
            <th>Num. Voo</th>
            <th>Status</th>
            <th>Tipo de Linha</th>
            <th>Origem</th>
            <th>Destino</th>
            <th></th>
        </tr>
    </thead>

    <tbody>

        {% for item in items %}

        <tr>
            <td>{{ item.pk }}
            <td>{{ item.sigla }}</td>
            <td>{{ item.numVoo }}</td>
            <td>{{ item.status }}</td>
            <td>{{ item.tipoLinha }}</td>
            <td>{{ item.origem }}</td>
            <td>{{ item.destino }}</td>

        </tr>

        {% endfor %}
    </tbody>
</table>

{% endblock %}

appprincipal/templates/historico.html
{% extends "historico_base.html" %}

{% block content %}
  <canvas id="items" width="300" height="300"></canvas>
{% endblock %}

{% block scripts %}
<script>
var ctx = document.getElementById("items");
var sigla = JSON.parse('{{ sigla|safe }}');
var situacao = JSON.parse('{{ situacao|safe }}');

var items = new Chart(ctx, {
    type: 'line',
    data: {
        labels: sigla,
        datasets: [{
            label: 'sigla',
            data: situacao,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
{% endblock %}

appprincipal/templates/historico_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Gráfico{% endblock %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
  </head>
  <body>
    {% block content %}

    {% endblock %}

    {% block scripts %}

    {% endblock %}
  </body>
</html>

appprincipal/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div>

    <h4>Historico de dados ANAC 2015-2019</h4>
</div>

<table class="table table-hover">
    <thead>

<a href="{% url 'appprincipal:historico' %}" class="btn btn-primary btn-md btn-trim" role="button"> Gráfico Voos Realizados X Empresa</a>
    </thead>
</br>
</br>
    <thead>

    <a href="{% url 'appprincipal:dashboard_with_pivot' %}" class="btn btn-primary btn-md btn-trim" role="button"> Dashboard Gráficos</a>
</thead>
    <tbody>

    </tbody>
</table>

{% endblock %}

appprincipal/templates/index2.html
<html>

    <meta charset="utf-8">

    <!-- Load d3.js -->
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/data.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

    <!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
    <link rel="stylesheet" type="text/css" href="//github.com/downloads/lafeber/world-flags-sprite/flags32.css" />


    <style>
        /* Add some padding on document's body to prevent the content
        to go underneath the header and footer */
        body{        
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .fixed-header, .fixed-footer{
            width: 100%;
            position: fixed;        
            background: #333;
            padding: 10px 0;
            color: #fff;
        }
        .fixed-header{
            top: 0;
        }
        .fixed-footer{
            bottom: 0;
        }
        .container{
            width: 80%;
            margin: 0 auto; /* Center the DIV horizontally */
        }
        nav a{
            color: #fff;
            text-decoration: none;
            padding: 7px 25px;
            display: inline-block;
        }
    </style>
    </head>
    <body>
        <div class="fixed-header">
            <div class>
                <nav>
                    <a href="/"><span style="font-size: 40px;">COVID-19 DashBoard</span></a>
                    
                </nav>
            </div>
        </div>
        <div>
            <div class="col-lg-3" style="float: left;  max-height: 650px;max-width:400px;overflow: scroll; overflow-x:hidden;">
                <div style="background-color: rgb(41, 41, 40);">
                    
                    <span style="color: rgb(255, 255, 255); text-align: center;"><h2>Total Infected: {{overallCount}}</h2></span>
                </div>
                <div class="col-lg-12">
                    <form method="post" enctype="multipart/form-data" action="selectCountry">
                    {% csrf_token %}
                    <div class="col-lg-4" style="float: left;">
                        {% for con in contryNames %}
                        <table style="border-width: 2px; border: #333;">
                        <tr>
                            <input type="submit" value={{con}} name="countryName" style="width:100px;">
                        </tr>
                    </table>
                        {% endfor %}
                    </div>
                    <div style="float: left;"> 
                        <canvas id="myChart" style="height: 6650px; width: 280px;"></canvas>
                    </div>
                    </form>
                    

                </div>
            </div>
            <div class="col-lg-6" style="float: left;">
                <br>
                <br> 
                <h2 style="text-align: center;">Analysis on {{countryName}}</h2><br>
                    <canvas id="lineChart" style="height: 450px;"></canvas>
            </div>
            <div class="col-lg-3" style="float: left;max-width: 300px;  max-height: 650px;overflow: scroll; overflow-x:hidden;">
                
            </div>
            </div>

        </div>
        <br>
        
            
    </body>

<script>

    var ctx = document.getElementById('myChart').getContext('2d');
    var chartOptions = {
                            legend: {
                                display: false
                                    },
                            scales: {
                                xAxes: [{
                                    barPercentage:1
                                    }],
                                yAxes: [
                                        // {barPercentage: 1},
                                        // {gridLines:{drawBorder: false}},
                                        {ticks: {display:false}},
                                        // {ticks: {mirror: true}},
                                        {display: false},
                                        
                                        ],
                            elements: {
                                rectangle: {
                                borderSkipped: 'left',
                                }
                            }
                            }
                        };
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'horizontalBar',

        // The data for our dataset
        data: {
            labels: {{ contryNames|safe }},
            datasets: [{
                data: {{ countsVal|safe }},
                label: 'Infected Counts',
                barThickness:'flex',
                backgroundColor:'#03a9fc',  
                
            }]
        },

        

        // Configuration options go here
        options: chartOptions
});
</script>

<script>
    var data2={{datasetsForLine|safe}};
    var chartOptions2 = {
            legend: {
                display: true
                    },
                    scales: {
						yAxes: [{
							type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
							display: true,
							position: 'left',
							id: 'y-axis-1',
						}, {
							type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
							display: true,
							position: 'right',
							id: 'y-axis-2',

							// grid line settings
							gridLines: {
								drawOnChartArea: false, // only want the grid lines for one axis to show up
							},
						}],
					},
        };
    var ctx2 = document.getElementById('lineChart').getContext('2d');  
	var myLineChart = new Chart(ctx2, {
        type: 'line',
        data: {labels:{{axisvalues|safe}},datasets:data2,},
        options: chartOptions2
        });
</script>

</html>